import nodemailer from "nodemailer";

export default async function handler(req, res) {
    // Add CORS headers so the Vercel deployed frontend can reach this API
    res.setHeader('Access-Control-Allow-Credentials', true);
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
    res.setHeader(
        'Access-Control-Allow-Headers',
        'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
    );

    // Handle OPTIONS request for preflight CORS
    if (req.method === 'OPTIONS') {
        res.status(200).end();
        return;
    }

    if (req.method !== 'POST') {
        return res.status(405).json({ success: false, message: 'Method Not Allowed' });
    }

    const { name, phone, email, message } = req.body;

    if (!name || !email || !message) {
        return res.status(400).json({ success: false, message: "Missing required fields." });
    }

    const transporter = nodemailer.createTransport({
        host: "smtp.gmail.com",
        port: 587,
        secure: false, // STARTTLS
        auth: {
            user: process.env.GMAIL_USER,
            pass: process.env.GMAIL_PASS,
        },
        tls: {
            rejectUnauthorized: false, // Helpful sometimes depending on deployment
        },
    });

    const mailOptions = {
        from: `"Salem Yogasana Contact" <${process.env.GMAIL_USER}>`,
        to: process.env.ADMIN_EMAIL,
        subject: `✉️ New Message from ${name}`,
        html: `
      <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: auto; border: 1px solid #e2e8f0; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.1);">
        <div style="background: linear-gradient(135deg, #0ea5e9, #2563eb); padding: 32px; text-align: center;">
          <h1 style="color: white; margin: 0; font-size: 24px; font-weight: 800; letter-spacing: -0.5px;">New Inquiry</h1>
          <p style="color: rgba(255,255,255,0.9); margin: 8px 0 0; font-size: 14px; font-weight: 500;">Salem Yogasana Festival 2026</p>
        </div>
        <div style="padding: 32px; background: #ffffff;">
          <table style="width: 100%; border-collapse: collapse;">
            <tr><td style="padding: 12px 0; color: #64748b; width: 30%; font-size: 14px;">👤 Name</td><td style="padding: 12px 0; font-weight: 700; color: #1e293b;">${name}</td></tr>
            <tr><td style="padding: 12px 0; color: #64748b; font-size: 14px;">📞 Phone</td><td style="padding: 12px 0; font-weight: 500; color: #1e293b;">${phone || "N/A"}</td></tr>
            <tr><td style="padding: 12px 0; color: #64748b; font-size: 14px;">📧 Email</td><td style="padding: 12px 0; font-weight: 500; color: #2563eb;">${email}</td></tr>
          </table>
          <div style="margin-top: 24px; padding: 20px; background: #f8fafc; border-radius: 12px; border: 1px solid #f1f5f9;">
            <p style="margin: 0 0 8px; color: #64748b; font-size: 12px; font-weight: 700; uppercase; letter-spacing: 0.5px;">Message Content:</p>
            <p style="margin: 0; color: #1e293b; font-size: 14px; line-height: 1.6; white-space: pre-wrap;">${message}</p>
          </div>
        </div>
        <div style="background: #f8fafc; padding: 20px; text-align: center; color: #94a3b8; font-size: 12px; border-top: 1px solid #f1f5f9;">
          © ${new Date().getFullYear()} Vasantham Yoga Center • Generated by G-Core Technologies
        </div>
      </div>
    `,
    };

    try {
        await transporter.sendMail(mailOptions);
        res.status(200).json({ success: true, message: "Inquiry received! Email sent." });
    } catch (err) {
        console.error("Email error:", err);
        res.status(500).json({ success: false, message: "Message sending failed." });
    }
}
